### ISSUE TITLE
Icon Image.

### ISSUE THREAD

**Issue by torounit** [torounit/hello-kushimoto#10]
Icon Image for plugin Installer.

ex. https://make.wordpress.org/core/2014/08/21/introducing-plugin-icons-in-the-plugin-installer/

@spicagraph

**Comment by spicagraph** [comment]
![introducing-plugin-icons](https://cloud.githubusercontent.com/assets/3328899/10941054/1282a36a-834d-11e5-8b18-ddba31a85537.png)
How did you like?

**Comment by torounit** [comment]
It's Funny!!!!

Please Pull Request assets branch! 
- icon-128x128.png
- icon-256x256.png
- icon.svg (optional)
